services:
  db:
    container_name: postgresfluxshop
    image: postgres
    restart: always
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pblnahupassword
      POSTGRES_DB: db_fluxshop
      POSTGRES_HOST_AUTH_METHOD: md5 #forzar metodo de auth md5 más compatible
    volumes:
      # - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database-tools/backups/db_fluxshop_backup_2025-07-02T23-59-47.sql:/docker-entrypoint-initdb.d/db_fluxshop_backup_2025-07-02T23-59-47.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fluxshop-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "db_fluxshop"]
      interval: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    container_name: mypgadmin
    image: dpage/pgadmin4
    restart: always
    #restart: unless-stopped #mejor politica de reinicio
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pblnahu@pblnahu.com
      PGADMIN_DEFAULT_PASSWORD: pblnahupassword
      #PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True" # seguridad
      #PGADMIN_CONFIG_LOGIN_BANNER: "Acceso restringido - Entorno de desarrollo" # mensaje personalizar
    #volumes:
      #- pgadmin_data:/var/lib/pgadmin # persistencia de config
      #- ./pgadmin-servers.json:/pgadmin4/servers.json # pre config server
    networks:
      - fluxshop-network
    depends_on:
      - db
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:80/login"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    container_name: server_fluxshop
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:pblnahupassword@db:5432/db_fluxshop
      - FRONTEND_URL=http://localhost:5173
      - NODE_ENV=development
    volumes:
      - ./server:/usr/src/app
    networks:
      - fluxshop-network

  web:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    container_name: client_fluxshop
    ports:
      - "5173:5173"
    depends_on:
      - server
    # volumes:
    #   - ./client:/usr/src/app
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    networks:
      - fluxshop-network

volumes:
  postgres_data:
  # pgadmin_data:
  #   name: pgadmin_fluxshop_data

networks:
  fluxshop-network:
    driver: bridge