services:
  db:
    container_name: postgresfluxshop
    image: postgres
    restart: always
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pblnahupassword
      POSTGRES_DB: db_fluxshop
      POSTGRES_HOST_AUTH_METHOD: md5 #forzar metodo de auth md5 más compatible
    volumes:
      # - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database-tools/backups/db_fluxshop_backup_2025-07-29T11-34-25.sql:/docker-entrypoint-initdb.d/db_fluxshop_backup_2025-07-29T11-34-25.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fluxshop-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "db_fluxshop"]
      interval: 5s
      retries: 5
      start_period: 10s

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    container_name: server_fluxshop
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:pblnahupassword@db:5432/db_fluxshop
      - FRONTEND_URL=http://localhost:5173
      - NODE_ENV=development
    volumes:
      - ./server:/usr/src/app
    networks:
      - fluxshop-network

  web:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    container_name: client_fluxshop
    ports:
      - "5173:5173"
    depends_on:
      - server
    # volumes:
    #   - ./client:/usr/src/app
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    networks:
      - fluxshop-network

volumes:
  postgres_data:

networks:
  fluxshop-network:
    external: true
    name: pgadmin-net