version: "3.8"

services:
  db:
    container_name: postgresfluxshop
    image: postgres
    restart: always
    ports:
      - "5444:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pblnahupassword
      POSTGRES_DB: db_fluxshop
      POSTGRES_HOST_AUTH_METHOD: md5 #forzar metodo de auth md5 más compatible
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fluxshop-network

  pgadmin:
    container_name: mypgadmin
    image: dpage/pgadmin4
    #restart: unless-stopped #mejor politica de reinicio
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pblnahu@pblnahu.com
      PGADMIN_DEFAULT_PASSWORD: pblnahupassword
      #PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True" # seguridad
      #PGADMIN_CONFIG_LOGIN_BANNER: "Acceso restringido - Entorno de desarrollo" # mensaje personalizar
    #volumes:
      #- pgadmin_data:/var/lib/pgadmin # persistencia de config
      #- ./pgadmin-servers.json:/pgadmin4/servers.json # pre config server
    #networks:
      #- fluxshop-network
    #depends_on:
      #- db
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:80/login"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  # server:

  # web:
  #   build: .
  #   command: npm run dev
  #   volumes:
  #     - .:/usr/app
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - db
  #   environment:
  #     - DB_USER=pblnahu
  #     - DB_PASSWORD=pblnahupassword
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - DB_DATABASE=db_fluxshop

volumes:
  postgres_data:
  # pgadmin_data:
  #   name: pgadmin_fluxshop_data

networks:
  fluxshop-network:
    name: fluxshop_network
    driver: bridge