# CREO UN NUEVO USUARIO con ROLE de ADMIN
POST http://localhost:3000/api/auth/create-account
Content-Type: application/json

{
    "email":"torrezadmin@gmail.com",
    "password":"123456",
    "username":"pabli_adin",
    "role_id":1
}

###

# Inicio SESION de ADMIN
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "torrezadmin@gmail.com",
    "password": "123456"
}

## -> RESPUESTA ESPERADA:
# {
#   "success": true,
#   "token": <TOKEN_GENERADO>,
#   "user": {
#     "id_u": 37,
#     "email": "torrezadmin@gmail.com",
#     "username": "pabli_adin",
#     "role_id": 1,
#     "role": "admin",
#     "permissions": [
#       "manage_users",
#       "view_users",
#       "create_users",
#       "update_users",
#       "delete_users",
#       "view_products",
#       "manage_products",
#       "create_products",
#       "update_products",
#       "delete_products",
#       "view_orders",
#       "manage_orders"
#     ],
#     "last_login": "2025-07-31T12:20:34.002Z"
#   }
# }


###

# CREO UN PRODUCTO como ADMINSITRADOR
POST http://localhost:3000/admin/products/create
Content-Type: application/json
Authorization: bearer <token>

{
    "name": "Logo personalizado",
    "description": "Este es un logo personalizado que podés usar en tu portfolio",
    "price": 9.99,
    "image": "products_screen/dark.jpg",
    "category": "Diseño Gráfico"
}

###

# ACTUALIZO un PRODUCTO EXISTENTE COMO ADMINISTRADOR
PUT http://localhost:3000/admin/products/update/6
Content-Type: application/json
Authorization: bearer <token>

{
    "price": 500.00
}

###

# ELIMINO UN PRODUCTO EXISTENTE COMO ADMINISTRADOR
DELETE http://localhost:3000/admin/products/delete/6
Authorization: bearer <token>