# crear usuario
POST http://localhost:3000/account/create-account
Content-Type: application/json

{
    "email": "usertest13@gmail.com",
    "password": "123456",
    "username": "usertest13"
}

### 

### login (user registered)
POST http://localhost:3000/account/login
Content-Type: application/json

{
    "email": "usertest13@gmail.com",
    "password": "123456"
}

###

### dashboard (route protected)
GET http://localhost:3000/dashboard/usertest13
Authorization: Bearer <token>

###

### carts

### para recuperar el carrito
GET http://localhost:3000/cart
Authorization: Bearer <token>

### para agregar productos al carrito
POST http://localhost:3000/cart
Content-Type: application/json
Authorization: Bearer <token>

{
    "productId": 1, 
    "quantity": 1
}


### para actualizar la cantidad de productos en el carrito
PUT http://localhost:3000/cart/11
Content-Type: application/json
Authorization: Bearer <token>

{
    "productId": 1,
    "quantity": 5
}

### para eliminar producto del carrito
DELETE http://localhost:3000/cart/1
Content-Type: application/json
Authorization: Bearer <token>

### para limpiar el carrito (borrar todo)
DELETE http://localhost:3000/cart/clear
Content-Type: application/json
Authorization: Bearer <token>

### para contar cuantos productos tengo
GET http://localhost:3000/cart/count
Content-Type: application/json
Authorization: Bearer <token>